# define / update pipeline definition
# fly sp -t lite -c git-node.yml -p git-node
# execute and watch the output from the job
# fly -t lite watch -j git-node/fake-todos-test
resources:
- name: fake-todos-git
  type: git
  source:
    uri: https://github.com/bahmutov/fake-todos.git
    branch: master
- name: fake-todos-concourse-git
  type: git
  source:
    uri: https://github.com/bahmutov/fake-todos-concourse.git
    branch: master
# jobs:
# - name: install
#   plan:
#     - get: fake-todos-git

jobs:
- name: fake-todos-test
  public: true
  plan:
    - get: fake-todos-git
    - get: fake-todos-concourse-git
    - task: test-fake-todos
      config:
        platform: linux
        image: docker:///mhart/alpine-node
        inputs:
          - name: fake-todos-git
            path: repo
          - name: fake-todos-concourse-git
            path: scripts
        run:
          path: ../scripts/npm-install.sh
          dir: repo
          # path: ls
          # args: [-laR]

# - task: hello-world
#   config:
#     platform: linux
#     image: docker:///mhart/alpine-node
#     inputs:
#       - name: fake-todos-git
#         path: repo
#     run:
#       path: npm
#       dir: repo
#       args: [test]
